const path = require('path');

const currentRoot = process.env.REVESBOT_APP_CURRENT || '/var/www/revesbot/app-current';
const appDir = path.join(currentRoot, 'apps', 'app');
const betWsDir = path.join(currentRoot, 'apps', 'bet_ws');
const houseAgentDir = path.join(currentRoot, 'apps', 'house_agent');

module.exports = {
  apps: [
    {
      name: 'revesbot-app',
      cwd: appDir,
      script: path.join(appDir, 'node_modules', 'next', 'dist', 'bin', 'next'),
      args: ['start', '-H', process.env.APP_HOST || '127.0.0.1', '-p', process.env.APP_PORT || '3002'],
      interpreter: 'node',
      instances: 1,
      autorestart: true,
      exp_backoff_restart_delay: 1000,
      restart_delay: 2000,
      kill_timeout: 15000,
      max_memory_restart: '1500M',
      time: true,
      env: {
        NODE_ENV: 'production',
        DEPLOY_STAGE: process.env.DEPLOY_STAGE || 'main',
        EXPRESS_URL: process.env.EXPRESS_URL,
        MONGO_URL: process.env.MONGO_URL,
        MONGO_DB: process.env.MONGO_DB,
        JWT_SECRET: process.env.JWT_SECRET,
        ENCRYPTION_KEY: process.env.ENCRYPTION_KEY,
        PIX_KEY: process.env.PIX_KEY,
        PIX_MERCHANT_NAME: process.env.PIX_MERCHANT_NAME,
        PIX_MERCHANT_CITY: process.env.PIX_MERCHANT_CITY,
        BET_WS_URL: process.env.BET_WS_URL,
        BET_WS_TOKEN: process.env.BET_WS_TOKEN,
        AUTOMATION_INTERNAL_TOKEN: process.env.AUTOMATION_INTERNAL_TOKEN,
        AUTO_TARGET_RATE_BPS: process.env.AUTO_TARGET_RATE_BPS,
        AUTO_MAX_LOSS_RATE_BPS: process.env.AUTO_MAX_LOSS_RATE_BPS,
        PIXGO_API_KEY: process.env.PIXGO_API_KEY,
        PIXGO_WEBHOOK_SECRET: process.env.PIXGO_WEBHOOK_SECRET,
        PIXGO_WEBHOOK_URL: process.env.PIXGO_WEBHOOK_URL,
        PIXGO_BASE_URL: process.env.PIXGO_BASE_URL,
        NEXT_PUBLIC_VIDEO_BASE: process.env.NEXT_PUBLIC_VIDEO_BASE,
        HOUSE_AGENT_URL: process.env.HOUSE_AGENT_URL,
        HOUSE_AGENT_TOKEN: process.env.HOUSE_AGENT_TOKEN,
        SUBSCRIPTION_ENABLED: process.env.SUBSCRIPTION_ENABLED,
        AUTOMATION_SIGNAL_SOURCE_ENABLED: process.env.AUTOMATION_SIGNAL_SOURCE_ENABLED,
        ORBIT_API_URL: process.env.ORBIT_API_URL,
      },
    },
    {
      name: 'revesbot-bet-ws',
      cwd: betWsDir,
      script: '/usr/bin/xvfb-run',
      args: ['-a', '-s', '-screen 0 1280x720x24', '/usr/bin/node', 'server.js'],
      interpreter: 'none',
      autorestart: true,
      exp_backoff_restart_delay: 1000,
      restart_delay: 2000,
      kill_timeout: 20000,
      max_memory_restart: '1200M',
      time: true,
      env: {
        NODE_ENV: 'production',
        BET_WS_HOST: process.env.BET_WS_HOST || '127.0.0.1',
        BET_WS_PORT: process.env.BET_WS_PORT || '4060',
        BET_WS_TOKEN: process.env.BET_WS_TOKEN,
        BASE_CHIP: process.env.BASE_CHIP || '0.5',
        SESSION_IDLE_TTL_MS: process.env.SESSION_IDLE_TTL_MS || '1800000',
        AUTOMATION_INTERNAL_TOKEN: process.env.AUTOMATION_INTERNAL_TOKEN,
        AUTOMATION_APP_URL: process.env.AUTOMATION_APP_URL || 'http://127.0.0.1:3002',
        PUPPETEER_EXECUTABLE_PATH: process.env.PUPPETEER_EXECUTABLE_PATH || '/usr/bin/chromium',
        PUPPETEER_HEADLESS: '0',
      },
    },
    {
      name: 'revesbot-house-agent',
      cwd: houseAgentDir,
      script: '/usr/bin/xvfb-run',
      args: ['-a', '-s', '-screen 0 1360x900x24', '/usr/bin/node', 'server.js'],
      interpreter: 'none',
      autorestart: true,
      exp_backoff_restart_delay: 1000,
      restart_delay: 2000,
      kill_timeout: 30000,
      max_memory_restart: '1800M',
      time: true,
      env: {
        NODE_ENV: 'production',
        HOUSE_AGENT_HOST: process.env.HOUSE_AGENT_HOST || '127.0.0.1',
        HOUSE_AGENT_PORT: process.env.HOUSE_AGENT_PORT || '4080',
        AGENT_TOKEN: process.env.HOUSE_AGENT_TOKEN,
        MAX_CONCURRENT: process.env.HOUSE_AGENT_MAX_CONCURRENT || '2',
        CHROME_BIN: process.env.CHROME_BIN || '/usr/bin/chromium',
      },
    },
  ],
};
