const path = require("path");

const stage = process.env.DEPLOY_STAGE;

if (!["develop", "main"].includes(stage)) {
  throw new Error(
    "DEPLOY_STAGE must be one of: develop, main"
  );
}

const repoRoot = process.env.REPO_ROOT || path.resolve(__dirname, "../..");
const pythonBin = process.env.PYTHON_BIN || path.join(repoRoot, ".venv", "bin", "python");
const isDevelop = stage === "develop";
const suffix = isDevelop ? "dev" : "prod";
const apiPort = process.env.API_PORT || (isDevelop ? "8081" : "8080");
const authApiPort = process.env.AUTH_API_PORT || (isDevelop ? "3091" : "3090");
const nodeEnv = isDevelop ? "development" : "production";

module.exports = {
  apps: [
    {
      name: `api-${suffix}`,
      cwd: repoRoot,
      script: "apps/api/start.py",
      interpreter: pythonBin,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      kill_timeout: 5000,
      time: true,
      env: {
        DEPLOY_STAGE: stage,
        PORT: apiPort,
        PYTHONUNBUFFERED: "1",
      },
    },
    {
      name: `collector-${suffix}`,
      cwd: path.join(repoRoot, "apps", "collector"),
      script: "main.py",
      interpreter: pythonBin,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      kill_timeout: 5000,
      time: true,
      env: {
        DEPLOY_STAGE: stage,
        PYTHONUNBUFFERED: "1",
      },
    },
    {
      name: `signals-${suffix}`,
      cwd: path.join(repoRoot, "apps", "signals"),
      script: "main.py",
      interpreter: pythonBin,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      kill_timeout: 5000,
      time: true,
      env: {
        DEPLOY_STAGE: stage,
        PYTHONUNBUFFERED: "1",
      },
    },
    {
      name: `monitoring-${suffix}`,
      cwd: path.join(repoRoot, "apps", "monitoring"),
      script: "main.py",
      interpreter: pythonBin,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      kill_timeout: 5000,
      time: true,
      env: {
        DEPLOY_STAGE: stage,
        PYTHONUNBUFFERED: "1",
      },
    },
    {
      name: `next-number-rankings-${suffix}`,
      cwd: repoRoot,
      script: "apps/monitoring/scripts/next_number_ranking_worker.py",
      interpreter: pythonBin,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      kill_timeout: 5000,
      time: true,
      env: {
        DEPLOY_STAGE: stage,
        PYTHONUNBUFFERED: "1",
        NEXT_NUMBER_RANKING_ROULETTE_ID: "pragmatic-auto-roulette",
        NEXT_NUMBER_RANKING_INTERVAL_SECONDS: "600",
      },
    },
    {
      name: `next-number-sequences-${suffix}`,
      cwd: repoRoot,
      script: "apps/monitoring/scripts/next_number_sequence_worker.py",
      interpreter: pythonBin,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      kill_timeout: 5000,
      time: true,
      env: {
        DEPLOY_STAGE: stage,
        PYTHONUNBUFFERED: "1",
        NEXT_NUMBER_SEQUENCE_ROULETTE_ID: "pragmatic-auto-roulette",
        NEXT_NUMBER_SEQUENCE_INTERVAL_SECONDS: "600",
      },
    },
    {
      name: `suggestion-snapshot-${suffix}`,
      cwd: repoRoot,
      script: "apps/monitoring/scripts/suggestion_snapshot_worker.py",
      interpreter: pythonBin,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      kill_timeout: 5000,
      time: true,
      env: {
        DEPLOY_STAGE: stage,
        PYTHONUNBUFFERED: "1",
        SUGGESTION_SNAPSHOT_STRATEGY_LOOKBACK: "60",
        SUGGESTION_SNAPSHOT_ROULETTES: "pragmatic-auto-roulette,pragmatic-brazilian-roulette,pragmatic-immersive-roulette-deluxe",
        PATTERN_ENGINE_USE_ADAPTIVE: "false",
      },
    },
    {
      name: `triplet-maintainer-${suffix}`,
      cwd: repoRoot,
      script: "apps/monitoring/scripts/triplet_maintainer.py",
      interpreter: pythonBin,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      kill_timeout: 5000,
      time: true,
      env: {
        DEPLOY_STAGE: stage,
        PYTHONUNBUFFERED: "1",
        TRIPLET_POLL_SECONDS: "2",
      },
    },
    {
      name: `triplet-strategy-${suffix}`,
      cwd: repoRoot,
      script: "apps/monitoring/scripts/triplet_strategy_worker.py",
      interpreter: pythonBin,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      kill_timeout: 5000,
      time: true,
      env: {
        DEPLOY_STAGE: stage,
        PYTHONUNBUFFERED: "1",
        TRIPLET_STRATEGY_POLL_SECONDS: "2",
      },
    },
    {
      name: `puxado-trigger-${suffix}`,
      cwd: repoRoot,
      script: "apps/monitoring/scripts/puxado_trigger_worker.py",
      interpreter: pythonBin,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      kill_timeout: 5000,
      time: true,
      env: {
        DEPLOY_STAGE: stage,
        PYTHONUNBUFFERED: "1",
        PUXADO_TRIGGER_POLL_SECONDS: "2",
      },
    },
    {
      name: `gatilho-worker-${suffix}`,
      cwd: repoRoot,
      script: "apps/monitoring/scripts/gatilho_worker.py",
      interpreter: pythonBin,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      kill_timeout: 5000,
      time: true,
      env: {
        DEPLOY_STAGE: stage,
        PYTHONUNBUFFERED: "1",
        GATILHO_POLL_SECONDS: "2",
        GATILHO_GENERATION_EVERY_N: "21",
        GATILHO_MIN_OCC: "5",
        GATILHO_MIN_PCT: "4.5",
        GATILHO_EXPIRE_MINUTES: "60",
      },
    },
    {
      name: `sinal-worker-${suffix}`,
      cwd: repoRoot,
      script: "apps/monitoring/scripts/sinal_worker.py",
      interpreter: pythonBin,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      kill_timeout: 5000,
      time: true,
      env: {
        DEPLOY_STAGE: stage,
        PYTHONUNBUFFERED: "1",
        SINAL_MAX_ATTEMPTS: "4",
        SINAL_EXPIRE_MINUTES: "60",
        SINAL_MIN_ASSERTIVENESS: "0.85",
        SINAL_GATE_MIN_FINALIZED: "5",
      },
    },
    {
      name: `auth-api-${suffix}`,
      cwd: path.join(repoRoot, "apps", "auth_api"),
      script: "dist/main.js",
      interpreter: "node",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      kill_timeout: 5000,
      time: true,
      env: {
        DEPLOY_STAGE: stage,
        NODE_ENV: nodeEnv,
        PORT: authApiPort,
      },
    },
    {
      name: `trio-ranking-worker-${suffix}`,
      cwd: repoRoot,
      script: "apps/monitoring/scripts/trio_ranking_worker.py",
      interpreter: pythonBin,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      kill_timeout: 5000,
      time: true,
      env: {
        DEPLOY_STAGE: stage,
        PYTHONUNBUFFERED: "1",
        TRIO_RANKING_ROULETTE_ID: "pragmatic-auto-roulette",
        TRIO_RANKING_HISTORY_COUNT: "5",
        TRIO_RANKING_TOP_NEXT1: "0",
        TRIO_RANKING_TOP_NEXT2: "0",
        TRIO_RANKING_TOP_NEXT3: "10",
        TRIO_RANKING_MAX_ATTEMPTS: "4",
        TRIO_RANKING_TOP_N_BET: "10",
        TRIO_RANKING_MAX_POST: "20",
        TRIO_RANKING_POLL_SECONDS: "2",
      },
    },
    {
      name: `occurrence-signal-worker-${suffix}`,
      cwd: repoRoot,
      script: "apps/monitoring/scripts/occurrence_signal_worker.py",
      interpreter: pythonBin,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      kill_timeout: 5000,
      time: true,
      env: {
        DEPLOY_STAGE: stage,
        PYTHONUNBUFFERED: "1",
        OCCURRENCE_SIGNAL_ROULETTE_IDS: "all",
        OCCURRENCE_SIGNAL_SPINS: "1000",
        OCCURRENCE_SIGNAL_ZERO_WINDOW: "7",
        OCCURRENCE_SIGNAL_TOP_N: "4",
        OCCURRENCE_SIGNAL_MAX_ATTEMPTS: "4",
        OCCURRENCE_SIGNAL_MAX_POST: "20",
        OCCURRENCE_SIGNAL_POLL_SECONDS: "2",
      },
    },
    {
      name: `terminal-7-signal-worker-${suffix}`,
      cwd: repoRoot,
      script: "apps/monitoring/scripts/terminal_7_signal_worker.py",
      interpreter: pythonBin,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      kill_timeout: 5000,
      time: true,
      env: {
        DEPLOY_STAGE: stage,
        PYTHONUNBUFFERED: "1",
        TERMINAL_7_ROULETTE_IDS: "all",
        TERMINAL_7_TRIGGER_VALUE: "34",
        TERMINAL_7_TERMINAL: "7",
        TERMINAL_7_NEIGHBOR_SPAN: "1",
        TERMINAL_7_MAX_ATTEMPTS: "2",
        TERMINAL_7_PRE_WINDOW: "5",
        TERMINAL_7_MAX_POST: "20",
        TERMINAL_7_POLL_SECONDS: "2",
      },
    },
    {
      name: `triplet-terminal-3pos-${suffix}`,
      cwd: repoRoot,
      script: "apps/monitoring/scripts/triplet_terminal_worker.py",
      interpreter: pythonBin,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      kill_timeout: 5000,
      time: true,
      env: {
        DEPLOY_STAGE: stage,
        PYTHONUNBUFFERED: "1",
        TRIPLET_TERMINAL_ROULETTE_IDS: "pragmatic-auto-roulette,pragmatic-brazilian-roulette,pragmatic-mega-roulette",
        TRIPLET_TERMINAL_POSITIONS: "3",
        TRIPLET_TERMINAL_SPINS: "500",
        TRIPLET_TERMINAL_PRE_WINDOW: "3",
        TRIPLET_TERMINAL_MAX_ATTEMPTS: "4",
        TRIPLET_TERMINAL_MAX_POST: "20",
        TRIPLET_TERMINAL_MIN_OCCUR: "3",
        TRIPLET_TERMINAL_MIN_SCORE: "3",
        TRIPLET_TERMINAL_NEIGHBOR_SPAN: "1",
        TRIPLET_TERMINAL_POLL_SECONDS: "2",
        TRIPLET_TERMINAL_BLOCKED_TERMINALS: "0,1,7",
      },
    },
    {
      name: `bot_automatico-${suffix}`,
      cwd: path.join(repoRoot, "apps", "bot_automatico"),
      script: "main.js",
      interpreter: "node",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      kill_timeout: 5000,
      time: true,
      env: {
        DEPLOY_STAGE: stage,
        NODE_ENV: nodeEnv,
      },
    },
  ],
};
