roulettes = [
    {"slug": "pragmatic-mega-roulette", "name": "Mega Roulette", "url": "https://lotogreen.bet.br/play/550"},
    {"slug": "pragmatic-brazilian-roulette", "name": "Brazilian Roulette", "url": "https://lotogreen.bet.br/play/450"},
    {"slug": "pragmatic-auto-roulette", "name": "Auto Roulette", "url": "https://lotogreen.bet.br/play/373"},
    {"slug": "pragmatic-auto-mega-roulette", "name": "Auto Mega Roulette", "url": "https://lotogreen.bet.br/play/543"},
    {"slug": "pragmatic-speed-roulette-1", "name": "Speed Roulette 1", "url": "https://lotogreen.bet.br/play/556"},
    {"slug": "pragmatic-mega-roulette-brazilian", "name": "Mega Roulette Brazilian", "url": "https://lotogreen.bet.br/play/6478"},
    {"slug": "pragmatic-speed-auto-roulette", "name": "Speed Auto Roulette", "url": "https://lotogreen.bet.br/play/457"},
    {"slug": "pragmatic-immersive-roulette-deluxe", "name": "Immersive Roulette Deluxe", "url": "https://lotogreen.bet.br/play/8261"},
    {"slug": "pragmatic-korean-roulette", "name": "Korean Roulette", "url": "https://lotogreen.bet.br/play/481"},
    {"slug": "pragmatic-lucky-6-roulette", "name": "Lucky Roulette", "url": "https://lotogreen.bet.br/play/6477"},
    {"slug": "evolution-immersive-roulette","name" : "Evolution Immersive Roulette", "url" : "https://lotogreen.bet.br/play/6253"},
    {"slug": "evolution-auto-roulette","name" : "Evolution Auto Roulette", "url" : "https://lotogreen.bet.br/play/6254"},
    {"slug": "evolution-american-roulette","name" : "Evolution American Roulette", "url" : "https://lotogreen.bet.br/6204"},
    {"slug": "evolution-auto-roulette-vip","name" : "Evolution Auto Roulette VIP", "url" : "https://lotogreen.bet.br/play/6256"},
    {"slug": "evolution-ruleta-relampago-en-vivo","name" : "Evolution Roleta Relâmpago ao Vivo", "url" : "https://lotogreen.bet.br/play/6287"},
    {"slug": "evolution-lightning-roulette","name" : "Evolution Lightning Roulette", "url" : "https://lotogreen.bet.br/play/6237"},
    {"slug": "evolution-roleta-ao-vivo","name" : "Evolution Roleta ao Vivo", "url" : "https://lotogreen.bet.br/play/6305"},
    {"slug": "evolution-roleta-relampago","name" : "Evolution Roleta Relâmpago", "url" : "https://lotogreen.bet.br/play/6313"},
    {"slug": "evolution-xxxtreme-lightning-roulette","name" : "Evolution XXXtreme Lightning Roulette", "url" : "https://lotogreen.bet.br/play/6301"},
    {"slug": "evolution-ruleta-bola-rapida-en-vivo","name" : "Evolution Bola Rápida ao Vivo", "url" : "https://lotogreen.bet.br/play/6298"},
    {"slug": "evolution-roulette","name" : "Evolution Roulette", "url" : "https://lotogreen.bet.br/play/6239"},
]