roulettes = [
    {"slug": "pragmatic-mega-roulette", "name": "Mega Roulette", "url": "https://lotogreen.bet.br/play/550"},
    {"slug": "pragmatic-brazilian-roulette", "name": "Brazilian Roulette", "url": "https://lotogreen.bet.br/play/450"},
    {"slug": "pragmatic-auto-roulette", "name": "Auto Roulette", "url": "https://lotogreen.bet.br/play/373"},
    {"slug": "pragmatic-auto-mega-roulette", "name": "Auto Mega Roulette", "url": "https://lotogreen.bet.br/play/543"},
    {"slug": "pragmatic-speed-roulette-1", "name": "Speed Roulette 1", "url": "https://lotogreen.bet.br/play/556"},
    {"slug": "pragmatic-mega-roulette-brazilian", "name": "Mega Roulette Brazilian", "url": "https://lotogreen.bet.br/play/6478"},
    {"slug": "pragmatic-speed-auto-roulette", "name": "Speed Auto Roulette", "url": "https://lotogreen.bet.br/play/481"},
    {"slug": "pragmatic-immersive-roulette-deluxe", "name": "Immersive Roulette Deluxe", "url": "https://lotogreen.bet.br/play/8261"},
    {"slug": "pragmatic-korean-roulette", "name": "Korean Roulette", "url": "https://lotogreen.bet.br/play/457"},
    {"slug": "pragmatic-lucky-6-roulette", "name": "Lucky Roulette", "url": "https://lotogreen.bet.br/play/6477"},
    {"slug": "pragmatic-roulette-macao", "name": "Roulette Macao", "url": "https://lotogreen.bet.br/play/552"},
    {"slug": "pragmatic-roulette-1", "name": "Roulette 1", "url": "https://lotogreen.bet.br/play/473"},
    {"slug": "pragmatic-roulette-2", "name": "Roulette 2", "url": "https://lotogreen.bet.br/play/457"},
    {"slug": "pragmatic-roulete-3", "name": "Roulette 3", "url": "https://lotogreen.bet.br/play/476"},
    {"slug": "pragmatic-vip-auto-roulette", "name": "VIP Auto Roulette", "url": "https://lotogreen.bet.br/play/457"},
    {"slug": "pragmatic-vip-roulette", "name": "VIP Roulette", "url": "https://lotogreen.bet.br/play/457"},
    {"slug": "pragmatic-turkish-mega-roulette", "name": "Turkish Mega Roulette", "url": "https://lotogreen.bet.br/play/457"},
    {"slug": "pragmatic-italian-mega-roulette", "name": "Italian Mega Roulette", "url": "https://lotogreen.bet.br/play/457"},
    {"slug": "pragmatic-turkish-roulette", "name": "Turkish Roulette", "url": "https://lotogreen.bet.br/play/457"},
    {"slug": "pragmatic-speed-roulette-2", "name": "Speed Roulette 2", "url": "https://lotogreen.bet.br/play/457"},
    {"slug": "pragmatic-romanian-roulette", "name": "Romanian Roulette", "url": "https://lotogreen.bet.br/play/457"},
    {"slug": "pragmatic-roulette-italian", "name": "Roulette Italian", "url": "https://lotogreen.bet.br/play/457"},
    {"slug": "pragmatic-german-roulette", "name": "German Roulette", "url": "https://lotogreen.bet.br/play/457"},
    {"slug": "pragmatic-russian-roulette", "name": "Russian Roulette", "url": "https://lotogreen.bet.br/play/457"},
    {"slug": "pragmatic-roulette-italia-tricolore", "name": "Roulette Italia Tricolore", "url": "https://lotogreen.bet.br/play/457"},
    {"slug": "pragmatic-vietnamese-roulette", "name": "Vietnamese Roulette", "url": "https://lotogreen.bet.br/play/457"},
]
